show mysql logs

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -9,8 +9,9 @@ env:
     - secure: "fBav56BzY+A+Vs1g9YSfo1oLDCO1rFrXl49lJkOA5/XpnsKEEs4lI2RcOzz0wiJKXFNgcliiAJWoYMI8Esqz+lkyFWan4ij5Co0UzJcytDuY+2o+jaqwx45DuDYPogABzT+hWjLCxQLLG46gUkChzT8kcvOOn6JxC7Ff8q5MnoM="
 
 before_script:
-  - set -o errexit # exit immediately when commands return a non-zero status
-  - sudo ls -l /var/log/mysql
+  #- set -o errexit # exit immediately when commands return a non-zero status
+  - sudo cp /var/log/mysql/err.log{,.orig}
+  - sudo cat /var/log/mysql/err.log
   - if [ "$SPRING_PROFILES_ACTIVE" = 'travis' ]; then
       mysql -u root -e 'CREATE DATABASE mystamps CHARACTER SET utf8;';
       mysql -u root -e "GRANT ALL PRIVILEGES ON mystamps.* TO 'travis'@'%';";
@@ -26,6 +27,7 @@ before_script:
         gem install danger nokogiri --no-ri --no-rdoc;
       fi;
     fi
+  - sudo diff -u /var/log/mysql/err.log{.orig,}
 
 script:
   - set -o errexit # exit immediately when commands return a non-zero status
